name       : kdsoap
version    : 1.9.0
release    : 3
source     :
    - https://github.com/KDAB/KDSoap/archive/kdsoap-1.9.0.tar.gz : da58f198ffe1ff25b5d4c59b9663c5f2d70bd79b17082bceb703bad6a233e0be
license    :
    - GPL-3.0-only
    - AGPL-3.0-only
component  : programming.library
summary    : KDSoap
description: |
    A Qt-based client-side and server-side SOAP component
builddeps  :
    - pkgconfig(Qt5Core)
patterns   :
    - devel : /usr/bin/kdwsdl2cpp
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
