name       : kdsoap
version    : 1.8.0
release    : 2
source     :
    - https://github.com/KDAB/KDSoap/archive/kdsoap-1.8.0.tar.gz : b3ad6fedf830810a4dde2228a9012bb38b61b02a05ae1781efbdc861763beb17
license    :
    - GPL-3.0-only
    - AGPL-3.0-only
component  : programming.library
summary    : KDSoap
description: |
    A Qt-based client-side and server-side SOAP component
builddeps  :
    - pkgconfig(Qt5Core)
patterns   :
    - devel : /usr/bin/kdwsdl2cpp
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
